Rails.application.routes.draw do
  devise_for :users
  root 'tests#index'
  get 'mypages/index', to: 'mypages#index'
  get 'mypages/profile', to: 'mypages#profile'
  get 'mypages/deliver_adress', to: 'mypages#deliver_adress'
  get 'mypages/card', to: 'mypages#card'
  get 'mypages/card_new', to: 'mypages#creditnew'
  get 'mypages/card_after', to: 'mypages#creditafter'
  get 'mypages/email_password', to: 'mypages#email_password'
  get 'mypages/identification', to: 'mypages#identification'
  get 'mypages/sms_confirmation', to: 'mypages#sms_confirmation'
  get 'mypages/logout', to: 'mypages#logout'
  get 'mypages/sales_transfer', to: 'mypages#sales_transfer'
  get 'mypages/points_confirmation', to: 'mypages#points_confirmation'
  get 'mypages/points_history', to: 'mypages#points_history'
  get 'mypages/points_limit', to: 'mypages#points_limit'
  get 'mypages/sales_history', to: 'mypages#sales_history'
  get 'mypages/sales_tra_lim', to: 'mypages#sales_tra_lim'
  get 'mypages/sales_tra_bank', to: 'mypages#sales_tra_bank'
  get 'mypages/sales_tra_history', to: 'mypages#sales_tra_history'
  get 'mypages/sales_tra_account_register', to: 'mypages#sales_tra_account_register'

  get 'tests/order_status', to: 'tests#order_status'
  get 'tests/item_detail', to: 'tests#item_detail'
  get 'tests/purchase_pre_confirmation', to: 'tests#purchase_pre_confirmation'
  get 'tests/purchase_confirmation', to: 'tests#purchase_confirmation'
  get 'tests/order_status_waiting', to: 'tests#order_status_waiting'
  get 'tests/putting_item', to: 'tests#putting_item'

  get 'mypage/top', to: 'mypages#mypage'
  get 'mypage/notification', to: 'mypages#mypage_notification'
  get 'mypage/todo', to: 'mypages#mypage_todo'
  get 'mypage/like/history', to: 'mypages#mypage_like_history'
  get 'mypage/listings/listing', to: 'mypages#mypage_listings_listing'
  get 'mypage/listings/in_progress', to: 'mypages#mypage_listings_in_progress'
  get 'mypage/listings/completed', to: 'mypages#mypage_listings_completed'
  get 'mypage/purchase', to: 'mypages#mypage_purchase'
  get 'mypage/purchased', to: 'mypages#mypage_purchased'
  get 'mypage/news', to: 'mypages#mypage_news'
  get 'mypage/review/history', to: 'mypages#mypage_review_history'
end
